In [1]:
import pandas as pd
import os

In [2]:
clean_covid_load = os.path.join("covid19_county_metrics_mod.csv")

In [3]:
co_covid_df = pd.read_csv(clean_covid_load)
co_covid_df

,county,date,One-Week Cumulative Incidence,Two-Week Cumulative Incidence,One-Week Average Positivity,Two-Week Average Positivity,County size
0,ADAMS,2/11/2022,225.0,648.8,0.099,0.130,">30,000"
1,ADAMS,2/10/2022,239.0,730.3,0.105,0.139,">30,000"
2,ADAMS,2/9/2022,283.8,830.3,0.117,0.150,">30,000"
3,ADAMS,2/8/2022,301.5,880.1,0.125,0.161,">30,000"
4,ADAMS,2/7/2022,318.6,941.0,0.129,0.169,">30,000"
...,...,...,...,...,...,...,...
44731,YUMA,3/19/2020,10.0,10.0,0.500,0.500,"30,000 or less"
44732,YUMA,3/18/2020,0.0,0.0,0.500,0.500,"30,000 or less"
44733,YUMA,3/17/2020,0.0,0.0,0.000,0.000,"30,000 or less"
44734,YUMA,3/16/2020,0.0,0.0,0.000,0.000,"30,000 or less"
44735,YUMA,3/15/2020,0.0,0.0,0.000,0.000,"30,000 or less"

In [4]:
co_covid_df = co_covid_df.rename(columns = {'county':'changeme'})
co_covid_df

,changeme,date,One-Week Cumulative Incidence,Two-Week Cumulative Incidence,One-Week Average Positivity,Two-Week Average Positivity,County size
0,ADAMS,2/11/2022,225.0,648.8,0.099,0.130,">30,000"
1,ADAMS,2/10/2022,239.0,730.3,0.105,0.139,">30,000"
2,ADAMS,2/9/2022,283.8,830.3,0.117,0.150,">30,000"
3,ADAMS,2/8/2022,301.5,880.1,0.125,0.161,">30,000"
4,ADAMS,2/7/2022,318.6,941.0,0.129,0.169,">30,000"
...,...,...,...,...,...,...,...
44731,YUMA,3/19/2020,10.0,10.0,0.500,0.500,"30,000 or less"
44732,YUMA,3/18/2020,0.0,0.0,0.500,0.500,"30,000 or less"
44733,YUMA,3/17/2020,0.0,0.0,0.000,0.000,"30,000 or less"
44734,YUMA,3/16/2020,0.0,0.0,0.000,0.000,"30,000 or less"
44735,YUMA,3/15/2020,0.0,0.0,0.000,0.000,"30,000 or less"

In [5]:
co_covid_df['County'] = co_covid_df['changeme'].astype(str) + ' County'
co_covid_df

,changeme,date,One-Week Cumulative Incidence,Two-Week Cumulative Incidence,One-Week Average Positivity,Two-Week Average Positivity,County size,County
0,ADAMS,2/11/2022,225.0,648.8,0.099,0.130,">30,000",ADAMS County
1,ADAMS,2/10/2022,239.0,730.3,0.105,0.139,">30,000",ADAMS County
2,ADAMS,2/9/2022,283.8,830.3,0.117,0.150,">30,000",ADAMS County
3,ADAMS,2/8/2022,301.5,880.1,0.125,0.161,">30,000",ADAMS County
4,ADAMS,2/7/2022,318.6,941.0,0.129,0.169,">30,000",ADAMS County
...,...,...,...,...,...,...,...,...
44731,YUMA,3/19/2020,10.0,10.0,0.500,0.500,"30,000 or less",YUMA County
44732,YUMA,3/18/2020,0.0,0.0,0.500,0.500,"30,000 or less",YUMA County
44733,YUMA,3/17/2020,0.0,0.0,0.000,0.000,"30,000 or less",YUMA County
44734,YUMA,3/16/2020,0.0,0.0,0.000,0.000,"30,000 or less",YUMA County
44735,YUMA,3/15/2020,0.0,0.0,0.000,0.000,"30,000 or less",YUMA County

In [6]:
co_covid_df.drop(['changeme'], axis=1, inplace=True)

In [7]:
co_covid_df

,date,One-Week Cumulative Incidence,Two-Week Cumulative Incidence,One-Week Average Positivity,Two-Week Average Positivity,County size,County
0,2/11/2022,225.0,648.8,0.099,0.130,">30,000",ADAMS County
1,2/10/2022,239.0,730.3,0.105,0.139,">30,000",ADAMS County
2,2/9/2022,283.8,830.3,0.117,0.150,">30,000",ADAMS County
3,2/8/2022,301.5,880.1,0.125,0.161,">30,000",ADAMS County
4,2/7/2022,318.6,941.0,0.129,0.169,">30,000",ADAMS County
...,...,...,...,...,...,...,...
44731,3/19/2020,10.0,10.0,0.500,0.500,"30,000 or less",YUMA County
44732,3/18/2020,0.0,0.0,0.500,0.500,"30,000 or less",YUMA County
44733,3/17/2020,0.0,0.0,0.000,0.000,"30,000 or less",YUMA County
44734,3/16/2020,0.0,0.0,0.000,0.000,"30,000 or less",YUMA County
44735,3/15/2020,0.0,0.0,0.000,0.000,"30,000 or less",YUMA County

In [12]:
co_covid_df = co_covid_df.rename(columns = {"One-Week Cumulative Incidence":"OneWeek_Cumulative_Incidence", "Two-Week Cumulative Incidence":"TwoWeek_Cumulative_Incidence", "One-Week Average Positivity":"OneWeek_Average Positivity", "Two-Week Average Positivity":"TwoWeek_Average_Positivity", "County size":"County_size"})

In [13]:
co_covid_df.to_csv('CleanCountyCoviddata.csv', columns=["County", "date", "OneWeek_Cumulative_Incidence", "TwoWeek_Cumulative_Incidence", "OneWeek_Average Positivity", "TwoWeek_Average_Positivity", "County_size"])